'use client';

import { useState, useEffect, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

const LOGO_URL = 'https://d64gsuwffb70l.cloudfront.net/6834a8f25630f332851529fb_1765418801539_cd77434c.png';

interface VerificationLog {
  id: string;
  requestingUserPhone: string;
  requestingUsername: string;
  token: string;
  tokenUsedAt: string;
  clientIp: string;
  dataDisclosed: string;
  legalAgreementAccepted: boolean;
  userAgent: string;
  viewedPersonId: string;
  requestingUserId: string;
  tokenGeneratedAt: string;
  legalAgreementVersion: string;
  auditType: string;
  auditSeverity: string;
}

interface VerificationData {
  logs: VerificationLog[];
  total: number;
}

export default function VerificationPage() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<VerificationData | null>(null);
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null);

  const fetchData = useCallback(async (token: string, showLoading = true) => {
    if (showLoading) setIsLoading(true);
    setError(null);
    try {
      const response = await fetch('/api/admin/verification-logs', {
        headers: { 'Authorization': `Bearer ${token}` },
      });

      if (!response.ok) {
        if (response.status === 401) {
          localStorage.removeItem('adminToken');
          router.push('/admin');
          return;
        }
        throw new Error('Failed to fetch data');
      }

      const result = await response.json();
      setData(result);
      setLastUpdated(new Date());
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error fetching data');
    } finally {
      setIsLoading(false);
    }
  }, [router]);

  useEffect(() => {
    const token = localStorage.getItem('adminToken');
    if (!token) {
      router.push('/admin');
      return;
    }
    fetchData(token);
  }, [router, fetchData]);

  const formatDate = (dateStr: string | null) => {
    if (!dateStr) return '—';
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const truncateText = (text: string, maxLength: number) => {
    if (!text) return '—';
    return text.length > maxLength ? `${text.substring(0, maxLength)}...` : text;
  };

  const handleShare = (log: VerificationLog) => {
    const subject = encodeURIComponent(`SnapfaceID Verification Audit Log - ${log.token}`);
    const body = encodeURIComponent(`
SNAPFACEID VERIFICATION AUDIT LOG
==================================

Token: ${log.token}
Date/Time: ${formatDate(log.tokenUsedAt)}

REQUESTING USER
---------------
Phone: ${log.requestingUserPhone}
Username: ${log.requestingUsername}
User ID: ${log.requestingUserId}

ACCESS DETAILS
--------------
Client IP: ${log.clientIp}
User Agent: ${log.userAgent}

DATA ACCESSED
-------------
Viewed Person ID: ${log.viewedPersonId}
Data Disclosed: ${log.dataDisclosed}

LEGAL COMPLIANCE
----------------
Agreement Accepted: ${log.legalAgreementAccepted ? 'Yes' : 'No'}
Agreement Version: ${log.legalAgreementVersion}
Audit Type: ${log.auditType}
Audit Severity: ${log.auditSeverity}

==================================
Generated by SnapfaceID Admin Dashboard
    `.trim());

    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  return (
    <div className="min-h-screen bg-gray-800">
      {/* Header */}
      <header className="bg-gray-700 border-b border-gray-600 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 py-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <img src={LOGO_URL} alt="SnapFace ID" className="h-8" />
              <div className="h-5 w-px bg-gray-500" />
              <h1 className="text-lg font-bold text-white">Verification Logs</h1>
              {lastUpdated && (
                <span className="text-xs text-gray-400 bg-gray-600 px-2 py-1 rounded">
                  {lastUpdated.toLocaleTimeString()}
                </span>
              )}
            </div>
            <div className="flex items-center gap-4">
              <span className="text-xs text-gray-400">
                {data?.total || 0} records
              </span>
              <Link
                href="/admin/dashboard"
                className="flex items-center gap-1 text-sm text-gray-300 hover:text-white bg-gray-600 hover:bg-gray-500 px-3 py-1.5 rounded-lg transition-colors"
              >
                <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
                Dashboard
              </Link>
            </div>
          </div>
        </div>
      </header>

      {/* Content */}
      <div className="max-w-7xl mx-auto px-4 py-4">
        {isLoading && (
          <div className="bg-gray-700 rounded-xl p-12 text-center">
            <div className="w-8 h-8 border-3 border-purple-500 border-t-transparent rounded-full animate-spin mx-auto mb-3" />
            <p className="text-gray-400 text-sm">Loading verification logs...</p>
          </div>
        )}

        {error && !isLoading && (
          <div className="bg-red-900/30 border border-red-700 rounded-xl p-6 text-center">
            <p className="text-red-400">{error}</p>
            <button
              onClick={() => {
                const token = localStorage.getItem('adminToken');
                if (token) fetchData(token);
              }}
              className="mt-3 text-sm text-purple-400 hover:text-purple-300"
            >
              Try again
            </button>
          </div>
        )}

        {!isLoading && !error && data && (
          <div className="bg-gray-700 rounded-xl overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="bg-gray-600/50 text-left">
                    <th className="px-3 py-3 text-xs font-semibold text-gray-300 uppercase tracking-wider">Phone</th>
                    <th className="px-3 py-3 text-xs font-semibold text-gray-300 uppercase tracking-wider">Username</th>
                    <th className="px-3 py-3 text-xs font-semibold text-gray-300 uppercase tracking-wider">Token</th>
                    <th className="px-3 py-3 text-xs font-semibold text-gray-300 uppercase tracking-wider">Used At</th>
                    <th className="px-3 py-3 text-xs font-semibold text-gray-300 uppercase tracking-wider">Client IP</th>
                    <th className="px-3 py-3 text-xs font-semibold text-gray-300 uppercase tracking-wider">Data</th>
                    <th className="px-3 py-3 text-xs font-semibold text-gray-300 uppercase tracking-wider">Legal</th>
                    <th className="px-3 py-3 text-xs font-semibold text-gray-300 uppercase tracking-wider">User Agent</th>
                    <th className="px-3 py-3 text-xs font-semibold text-gray-300 uppercase tracking-wider">Person ID</th>
                    <th className="px-3 py-3 text-xs font-semibold text-gray-300 uppercase tracking-wider w-16">Share</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-600">
                  {data.logs.length === 0 ? (
                    <tr>
                      <td colSpan={10} className="px-4 py-12 text-center text-gray-500">
                        No verification logs found
                      </td>
                    </tr>
                  ) : (
                    data.logs.map((log) => (
                      <tr key={log.id} className="hover:bg-gray-600/50">
                        <td className="px-3 py-3">
                          <span className="text-sm text-gray-300 font-mono">{log.requestingUserPhone || '—'}</span>
                        </td>
                        <td className="px-3 py-3">
                          <span className="text-sm font-medium text-white">{truncateText(log.requestingUsername, 12)}</span>
                        </td>
                        <td className="px-3 py-3">
                          <span className="text-xs text-purple-400 font-mono bg-purple-900/30 px-1.5 py-0.5 rounded">{log.token}</span>
                        </td>
                        <td className="px-3 py-3">
                          <span className="text-sm text-gray-400">{formatDate(log.tokenUsedAt)}</span>
                        </td>
                        <td className="px-3 py-3">
                          <span className="text-xs text-gray-400 font-mono">{log.clientIp || '—'}</span>
                        </td>
                        <td className="px-3 py-3">
                          <span className="text-xs text-green-400">{log.dataDisclosed}</span>
                        </td>
                        <td className="px-3 py-3">
                          {log.legalAgreementAccepted ? (
                            <span className="text-xs text-green-400 font-medium">Yes</span>
                          ) : (
                            <span className="text-xs text-red-400 font-medium">No</span>
                          )}
                        </td>
                        <td className="px-3 py-3">
                          <span className="text-xs text-gray-500" title={log.userAgent}>
                            {truncateText(log.userAgent, 20)}
                          </span>
                        </td>
                        <td className="px-3 py-3">
                          <span className="text-xs text-gray-400 font-mono">{truncateText(log.viewedPersonId, 10)}</span>
                        </td>
                        <td className="px-3 py-3 text-center">
                          <button
                            onClick={() => handleShare(log)}
                            className="p-1.5 rounded-lg bg-gray-600 hover:bg-purple-600 text-gray-400 hover:text-white transition-colors"
                            title="Share via Email"
                          >
                            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
                            </svg>
                          </button>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
